alert("Bienvenido a mi pagina de JavaScript")
alert("Para continuar necesito validar tus datos")
let nombre = prompt("¿Cual es tu nombre?")
let apellido = prompt("¿Cual es tu apellido?")
let edad = parseInt(prompt("Cuantos años tienes"))
alert("Muchas gracias por validar tu informacion")
alert("Mientras validamos tu informacion cuantanos un poco mas acerca de ti")
let colorFavorito = prompt("¿Cual es tu color favorito?")
alert("Espera terminamos de validar tu informacion")
alert("Lo siento con la informacion que nos brindaste no hemos podido validar que no eres un robot")
alert("Es una mentira jajaja")
alert("Mi color favorito tambien es el " + colorFavorito +" <3")
let bienvenida = "Bienvenido " + nombre + " " + apellido + ". Puedes continuar"
alert(bienvenida)
